### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by lujiayou123** [justinjfu/inverse_rl#8]
Thank you very much for releasing your code. When I run ant_data_collect.py , some problem occured:

python ant_data_collect.py 
2019-03-25 15:35:17.709269 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
2019-03-25 15:35:17.709250 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
2019-03-25 15:35:17.709358 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
2019-03-25 15:35:17.709459 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/utils/hyper_sweep.py", line 47, in kwargs_wrapper
    return method(**args)
  File "ant_data_collect.py", line 16, in main
    env = TfEnv(CustomGymEnv('CustomAnt-v0', record_video=False, record_log=False, force_reset=False))
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/env_utils.py", line 123, in __init__
    video_schedule=FixedIntervalVideoSchedule(50), force_reset=force_reset)
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/env_utils.py", line 35, in __init__
    env = gym.envs.make(env_name)
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/registration.py", line 87, in make
    env = cls(**_kwargs)
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/ant_env.py", line 209, in __init__
    mujoco_env.MujocoEnv.__init__(self, f.name, 5)
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/dynamic_mjc/model_builder.py", line 57, in asfile
    yield f
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/ant_env.py", line 209, in __init__
    mujoco_env.MujocoEnv.__init__(self, f.name, 5)
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/mujoco/mujoco_env.py", line 42, in __init__
    observation, _reward, done, _info = self.step(np.zeros(self.model.nu))
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/core.py", line 62, in step
    raise NotImplementedError
NotImplementedError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ant_data_collect.py", line 41, in <module>
    run_sweep_parallel(main, params_dict, repeat=4)
  File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/utils/hyper_sweep.py", line 57, in run_sweep_parallel
    pool.map(kwargs_wrapper, exp_args)
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
NotImplementedError
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

**Comment by akshaysarvesh25** [comment]
I have the same error and I am not able to fix it. Were you able to fix it @lujiayou123 ? I was wondering if the problem is because of python dependencies in my machine and replicated the entire installation of gym, rllab and finally running your code. The problem still persists. Any suggestions @justinjfu ?

**Comment by weihongwei0586** [comment]
I have the same error too, have you solved it?

**Comment by weihongwei0586** [comment]
> Thank you very much for releasing your code. When I run ant_data_collect.py , some problem occured:
> 
> python ant_data_collect.py
> 2019-03-25 15:35:17.709269 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
> 2019-03-25 15:35:17.709250 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
> 2019-03-25 15:35:17.709358 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
> 2019-03-25 15:35:17.709459 CST | Warning: skipping Gym environment monitoring since snapshot_dir not configured.
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 119, in worker
> result = (True, func(*args, **kwds))
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
> return list(map(*args))
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/utils/hyper_sweep.py", line 47, in kwargs_wrapper
> return method(**args)
> File "ant_data_collect.py", line 16, in main
> env = TfEnv(CustomGymEnv('CustomAnt-v0', record_video=False, record_log=False, force_reset=False))
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/env_utils.py", line 123, in **init**
> video_schedule=FixedIntervalVideoSchedule(50), force_reset=force_reset)
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/env_utils.py", line 35, in **init**
> env = gym.envs.make(env_name)
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/registration.py", line 171, in make
> return registry.make(id, **kwargs)
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/registration.py", line 123, in make
> env = spec.make(**kwargs) File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/registration.py", line 87, in make env = cls(**_kwargs)
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/ant_env.py", line 209, in **init**
> mujoco_env.MujocoEnv.**init**(self, f.name, 5)
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/contextlib.py", line 77, in **exit**
> self.gen.throw(type, value, traceback)
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/dynamic_mjc/model_builder.py", line 57, in asfile
> yield f
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/envs/ant_env.py", line 209, in **init**
> mujoco_env.MujocoEnv.**init**(self, f.name, 5)
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/envs/mujoco/mujoco_env.py", line 42, in **init**
> observation, _reward, done, _info = self.step(np.zeros(self.model.nu))
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/site-packages/gym/core.py", line 62, in step
> raise NotImplementedError
> NotImplementedError
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "ant_data_collect.py", line 41, in
> run_sweep_parallel(main, params_dict, repeat=4)
> File "/home/sylyvahn/Downloads/AIRL-ahq1993/inverse_rl-master/inverse_rl/utils/hyper_sweep.py", line 57, in run_sweep_parallel
> pool.map(kwargs_wrapper, exp_args)
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 260, in map
> return self._map_async(func, iterable, mapstar, chunksize).get()
> File "/home/sylyvahn/anaconda3/envs/rllab/lib/python3.5/multiprocessing/pool.py", line 608, in get
> raise self._value
> NotImplementedError
> Exception ignored in: <_io.TextIOWrapper name='' mode='w' encoding='UTF-8'>
> BrokenPipeError: [Errno 32] Broken pipe

I have solved this error and pass the first 'ant_* 'demo.
This error is caused by the conflicts of versions between mujoco and gym
First, you should konw that the experiments in this paper was performed in 2017. The version mujoco should use '0.5.0' and the version of gym is '0.7.+', you can install mujoco by command 'pip install mujoco-py==0.5.0'.
